# inventory/group_vars/aws_ec2.yml
#
# aws_ec2.yml (動的インベントリプラグイン) で取得した
# 全てのホストに適用されます

# 接続方法としてAWS SSMを指定
ansible_connection: aws_ssm

# SSMセッション実行時のOSユーザー
# ssm-userはSSM Agentによって作成されます
ansible_user: ssm-user

# AWS認証情報を指定
ansible_aws_ssm_profile: default

# ターゲットインスタンスが存在するリージョンを指定
ansible_aws_ssm_region: us-west-2

# SSMセッションログをS3に保存する場合のバケット名
# terraform.tfvarsに記載したname_prefix（autoops2の部分）に置き換えてください
ansible_aws_ssm_bucket_name: autoops2-s3-ssm

# Pythonインタプリタのパスを明示的に指定して警告を抑制
# ターゲットOSの環境に合わせて設定してください。
# ansible_python_interpreter: /usr/bin/python3.9
